version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build-and-test:
    working_directory: ~/market/frontend
    executor:
      name: node/default
      tag: '16.19'
    steps:
      - checkout:
          path: ~/market
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test