version: 2.1

jobs:
  build-and-test:
    orbs:
      node: circleci/node@16.0
    working_directory: ~/market/frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/market
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test