version: 2.1

jobs:
  build-and-test:
    working_directory: ~/Anythink-Market-a2sp4/frontend
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout:
          path: ~/Anythink-Market-a2sp4
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test